name: Copiar rama del Repositorio A al Repositorio B

on:
  workflow_dispatch:

jobs:
    copy-content:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout repositorio 2023.05.29.demo
            uses: actions/checkout@v2
            with:
                repository: dramon-z/2023.05.29.demo
                ref: master
                token: ${{secrets.GLOBAL_REPO_TOKEN}}

          - name: Crear repositorio B
            run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"
                ls
                echo "##CLONE REPO"
                git clone https://github.com/dramon-z/test_git_actions.git # Clonar el repositorio B
                ls
                

          - name: Copiar archivos
            run: |
                cd test_git_actions # Entrar al repositorio B
                ls
                # git checkout master # Cambiar a la rama de destino en el repositorio B
                # cp -R ../2023.05.29.demo/* . # Copiar los archivos de la rama de origen al repositorio B
                # git add .
                # git commit -m "Copiar archivos de la rama source-branch del repositorio A"
                # git push origin main # Empujar los cambios a la rama de destino en el repositorio B    
