name: Copiar rama del Repositorio A al Repositorio B

on:
  workflow_dispatch:

jobs:
  copy-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio A
        uses: actions/checkout@v2
        with:
          repository: dramon-z/test_git_actions
          ref: master
          token: ${{ secrets.GLOBAL_REPO_TOKEN }}

      - name: Checkout repositorio B
        uses: actions/checkout@v2
        with:
          repository: dramon-z/2023.05.29.demo
          ref: master
          token: ${{ secrets.GLOBAL_REPO_TOKEN }}

      - name: Copiar contenido
        run: |
          ls
          echo "####"
          git remote add dramon-z/test_git_actions .
          ls
          echo "####"
          git status
          git push dramon-z/test_git_actions HEAD:master
          ls
