name: Copiar rama del Repositorio A al Repositorio B

on:
  workflow_dispatch:

jobs:
    copy-content:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout repositorio 2023.05.29.demo
            uses: actions/checkout@v2
            with:
                repository: dramon-z/2023.05.29.demo
                ref: master
                token: ${{secrets.GLOBAL_REPO_TOKEN}}

          - name: Copiar contenido a carpeta temporal
            run: |
                mkdir temp
                cp -R ./* temp/

          - name: Checkout repositorio test_git_actions
            uses: actions/checkout@v2
            with:
                repository: dramon-z/test_git_actions
                ref: master
                token: ${{secrets.GLOBAL_REPO_TOKEN}}

          - name: Copiar contenido de carpeta temporal a repositorio test_git_actions
            run: |
                cp -R ./temp/* .
                rm -rf temp/

          - name: Commit y push cambios
            run: |
                git add .
                git commit -m "Copiar contenido de rama master de dramon-z/2023.05.29.demo"
                git push