name: Copiar rama del Repositorio A al Repositorio B

on:
  workflow_dispatch:

jobs:
  copy-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio A
        uses: actions/checkout@v2
        with:
          repository: dramon-z/test_git_actions
          ref: master
          token: ${{ secrets.GLOBAL_REPO_TOKEN }}

      - name: Checkout repositorio B
        uses: actions/checkout@v2
        with:
          repository: dramon-z/2023.05.29.demo
          ref: master
          token: ${{ secrets.GLOBAL_REPO_TOKEN }}

      - name: Copiar contenido
        run: |
          git remote show origin
          ls
          echo "####"
          git remote set-url origin https://github.com/dramon-z/test_git_actions
          echo "####"
          git remote show origin
          echo "####"
          ls
          echo "####"
          git status
          git add .
          git commit -m "change"
          git push
          #git push dramon-z/test_git_actions HEAD:master
          
          echo "####"
          git remote show origin
          ls
