name: check-repository

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Nombre del tag'
        required: false
      servicename:
          description: 'Nombre del servicio'
          required: true

jobs:
  job0:
    runs-on: ubuntu-latest
    # outputs:
    #   REPOSITORIOS: ${{ steps.leer-yaml.outputs.REPOSITORIOS }}
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
      
      - name: Leer archivo YAML
        id: leer-yaml
        run: |
          servicename=${{ github.event.inputs.servicename }}   
          
          content=$(cat repositorios/${servicename}.json)
          echo "$content"       
          risk=$(echo $content | jq -r '.risk')
          repo_https=$(echo $content | jq -r '.repo_https')
          echo "El riesgo es: $risk"
          echo "El repo https: $repo_https "


          repo_url_ssh=$(echo $content | jq -r '.repo_url_ssh')
          string="$repo_url_ssh"

          # Extraer el usuario
          usuario=${string#*@}  # Eliminar todo antes del símbolo '@'
          usuario=${usuario%%/*}  # Eliminar todo después del símbolo '/'
          
          # Extraer el repositorio
          repositorio=${string#*/}  # Eliminar todo antes del primer símbolo '/'
          repositorio=${repositorio%.git}  # Eliminar la extensión '.git'
          
          echo "Usuario: $usuario"
          echo "Repositorio: $repositorio"


          echo "RISK=$risk" >> $GITHUB_ENV  
      
      - name: Mostrar riesgo del repositorio
        run: |
          risk=$RISK
          echo "El riesgo del repositorio ${{ github.event.inputs.servicename }} es: $risk"    
          
          


          
      #     yaml=$(<repositorios.yml)          
      #     risk=$(echo "$yaml" | yq eval ".repositorios[] | select(.name == \"$repository\") | .risk" -)
      #     echo "RISK=$risk" >> $GITHUB_ENV  
      
      # - name: Mostrar riesgo del repositorio
      #   run: |
      #     risk=$RISK
      #     echo "El riesgo del repositorio ${{ github.event.inputs.repository }} es: $risk"
