name: Verificar Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Nombre del tag'
        required: true
      repositorio:
        description: 'Nombre del repositorio (en formato "usuario/repositorio")'
        required: true

jobs:
  verificar-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar Tag
        id: verificar-tag
        run: |
          tag_exists=$(curl -s "https://api.github.com/repos/${{ github.event.inputs.repositorio }}/git/refs/tags/${{ github.event.inputs.tag }}")
          echo "::set-output name=tag_exists::${tag_exists}"
      - name: Imprimir Resultado
        run: |
          if [[ "${{ steps.verificar-tag.outputs.tag_exists }}" == "null" ]]; then
            echo "El tag ${{ github.event.inputs.tag }} NO existe en el repositorio ${{ github.event.inputs.repositorio }}"
          else
            echo "El tag ${{ github.event.inputs.tag }} existe en el repositorio ${{ github.event.inputs.repositorio }}"
          fi