name: test

on:
  workflow_dispatch:

jobs:
#   job0:
#     name: Create repository for code
#     uses: dramon-z/refactor_repo/.github/workflows/refactor_repository.yaml@master
#     with:
#         servicename: 'Test1'
#         version: '1.0.0'
#         repo_env: 'dev'
#         repo_appid: 'uuid'
#         repo_host: 'localhost'
#         business_unit: 'spin'
#         podname: 'AQUILA'
#     secrets: inherit
  job1:
    runs-on: ubuntu-latest
    steps: 
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v2
          with:
            token: ${{ secrets.GLOBAL_REPO_TOKEN }}
            repository: dramon-z/refactor_repo
            event-type: refactor_repository
            client-payload: '{"servicename": "1","version": "2","repo_env": "3","repo_appid": "4","repo_host": "5",    "business_unit": "6","podname": "7"}'
#       - name: mod repository
#         run: |      
          
#           response=$(curl -X POST https://api.github.com/repos/dramon-z/refactor_repo/dispatches \
#             -H 'Accept: application/vnd.github.everest-preview+json' \
#             --header 'Authorization: Bearer ${{ secrets.GLOBAL_REPO_TOKEN }}' \
#             --write-out "HTTP Status Code: %{http_code}\n\n%{response_code}" \ # Captura el código de estado y el cuerpo de respuesta
#             --silent \ # Suprime la salida estándar
#             --show-error) # Muestra errores en la salida estándar
#           echo "$response"
