name: test

on:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    steps: 
#         - name: Repository Dispatch
#           uses: peter-evans/repository-dispatch@v2
#           with:
#             token: ${{ secrets.GLOBAL_REPO_TOKEN }}
#             repository: dramon-z/refactor_repo
#             event-type: refactor_repository
#             client-payload: '{"servicename": "1","version": "2","repo_env": "3","repo_appid": "4","repo_host": "5",    "business_unit": "6","podname": "7"}'
      - name: mod repository
        run: |           
          response=$(curl --location 'https://api.github.com/repos/dramon-z/refactor_repo/dispatches' \
            --header 'Accept: application/vnd.github.v3+json' \
            --header 'Authorization: Bearer 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' \
            --header 'Content-Type: application/json' \
            --data '{
                "event_type": "refactor_repository",
                "client_payload": {
                    "servicename": "test",
                    "version": "1.0.0",
                    "repo_env": "dev",
                    "repo_appid": "UUID",
                    "repo_host": "localhost",
                    "business_unit": "spin",
                    "podname": "AQUILA"
                }
            }' \
            -w "\nHTTP Status Code: %{http_code}\n\n%{response_code}\n")
          echo "$response"
